services:
  - type: web
    name: resume-screener-ai
    env: docker
    repo: https://github.com/110-0011/resume-screener-ai
    branch: main  # adjust if you're using another branch
    plan: free    # or standard/starter
    autoDeploy: true
    envVars:
      - key: QDRANT_URL
        fromSecret: QDRANT_URL
      - key: QDRANT_API_KEY
        fromSecret: QDRANT_API_KEY
